#!/command/with-contenv sh
# shellcheck shell=sh

echo '
───────────────────────────────────────
To get support, please go to:
https://github.com/llaumgui/seedboxsync

───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u seedboxsync)
User GID:    $(id -g seedboxsync)
───────────────────────────────────────"
