name: Publish GitHub Pages

on:
  push:
    tags: ['*']
    #branches:
    #  - develop
    #  - main

env:
  pythonLastVersion: '3.14'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy documentation using ProperDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      # Setup Python
      - name: Install Just
        uses: taiki-e/install-action@just
      - name: Setup Python ${{ env.pythonLastVersion }} with uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ env.pythonLastVersion }}
      # Instal & run task
      - name: Install Python dependencies
        run: just python-install-dev
      # Deploy documentation
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v6
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - name: Deploy ProperDocs
        run: just doc-gh-deploy